apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fahclient
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: fahclient
    spec:
      containers:
      - name: fahclient
        image: makisho/fahclient:latest
